repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: check-added-large-files
        args: ['--maxkb=512']
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
        files: \.(c|cc|cxx|cpp|cu|h|hpp|hxx|py)$
-   repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
    -   id: remove-crlf
    -   id: remove-tabs
        files: \.(c|cc|cxx|cpp|cu|h|hpp|hxx|py)$
-   repo: local
    hooks:
    -   id: clang-format
        name: clang-format
        args: [--style=Google]
        files: \.(c|cc|cxx|cpp|cu|h|hpp|hxx|cuh|proto)$
        description: Format files with ClangFormat
        entry: bash .clang_format.hook -i
        language: system
